import { HexModel } from "./hex.model";
import { G } from '@svgdotjs/svg.js';

export class BoardModel {
  boardState: Map<String, HexModel> = new Map()
  emptyHex = new G()
  static staticHexes: Array<HexModel> = [
    // map constructed starting left top corner, moving downward, then right, then down, etc.
    // new HexModel('A', '3', { raw: PLE }),
    // new HexModel('A', '7'),
    // new HexModel('A', '13'),
    // new HexModel('B', '2'),
    // new HexModel('B', '4'),
    // new HexModel('B', '6'),
    // new HexModel('B', '8'),
    // new HexModel('B', '10'),
    // new HexModel('B', '12'),
    // new HexModel('B', '14'),
    // new HexModel('C', '3'),
    // new HexModel('C', '5'),
    // new HexModel('C', '7'),
    // new HexModel('C', '9'),
    // new HexModel('C', '11'),
    // new HexModel('C', '13'),
    // new HexModel('D', '2'),
    // new HexModel('D', '4'),
    // new HexModel('D', '6'),
    // new HexModel('D', '8'),
    // new HexModel('D', '10'),
    // new HexModel('D', '12'),
    // new HexModel('E', '1'),
    // new HexModel('E', '3'),
    // new HexModel('E', '5'),
    // new HexModel('E', '7'),
    // new HexModel('E', '9'),
    // new HexModel('E', '11'),
    // new HexModel('E', '13'),
    // new HexModel('F', '2'),
    // new HexModel('F', '4'),
    // new HexModel('F', '6'),
    // new HexModel('F', '8'),
    // new HexModel('F', '10'),
    // new HexModel('F', '12'),
    // new HexModel('F', '14'),
    // new HexModel('G', '1'),
    // new HexModel('G', '3'),
    // new HexModel('G', '5'),
    // new HexModel('G', '7'),
    // new HexModel('G', '9'),
    // new HexModel('G', '11'),
    // new HexModel('G', '13'),
    // new HexModel('H', '2'),
    // new HexModel('H', '4'),
    // new HexModel('H', '6'),
    // new HexModel('H', '12'),
    // new HexModel('H', '14'),
    // new HexModel('I', '3'),
    // new HexModel('I', '5'),
    // new HexModel('I', '7'),
    // new HexModel('I', '9'),
    // new HexModel('J', '2'),
    // new HexModel('J', '4'),
    // new HexModel('J', '6'),
    // new HexModel('J', '8'),
    // new HexModel('J', '10'),
    // new HexModel('K', '1'),
    // new HexModel('K', '3'),
    // new HexModel('K', '5'),
    // new HexModel('K', '7'),
    // new HexModel('L', '2'),
    // new HexModel('L', '4')
  ];

}
