// initial map
import A3 from '../../assets/initial-hexes/A3.svg'
import A7 from '../../assets/initial-hexes/A7.svg'
import A13 from '../../assets/initial-hexes/A13.svg'
import B2 from '../../assets/initial-hexes/B2.svg'
import B14 from '../../assets/initial-hexes/B14.svg'
import C5 from '../../assets/initial-hexes/C5.svg'
import C13 from '../../assets/initial-hexes/C13.svg'
import D2 from '../../assets/initial-hexes/D2.svg'
import D8 from '../../assets/initial-hexes/D8.svg'
import D12 from '../../assets/initial-hexes/D12.svg'
import E1 from '../../assets/initial-hexes/E1.svg'
import E3 from '../../assets/initial-hexes/E3.svg'
import E11 from '../../assets/initial-hexes/E11.svg'
import F2 from '../../assets/initial-hexes/F2.svg'
import F4 from '../../assets/initial-hexes/F4.svg'
import F8 from '../../assets/initial-hexes/F8.svg'
import F14 from '../../assets/initial-hexes/F14.svg'
import G1 from '../../assets/initial-hexes/G1.svg'
import G3 from '../../assets/initial-hexes/G3.svg'
import G5 from '../../assets/initial-hexes/G5.svg'
import G13 from '../../assets/initial-hexes/G13.svg'
import H2 from '../../assets/initial-hexes/H2.svg'
import H4 from '../../assets/initial-hexes/H4.svg'
import H6 from '../../assets/initial-hexes/H6.svg'
import H14 from '../../assets/initial-hexes/H14.svg'
import I3 from '../../assets/initial-hexes/I3.svg'
import I5 from '../../assets/initial-hexes/I5.svg'
import I9 from '../../assets/initial-hexes/I9.svg'
import J2 from '../../assets/initial-hexes/J2.svg'
import J4 from '../../assets/initial-hexes/J4.svg'
import J6 from '../../assets/initial-hexes/J6.svg'
import K1 from '../../assets/initial-hexes/K1.svg'
import K3 from '../../assets/initial-hexes/K3.svg'
import K5 from '../../assets/initial-hexes/K5.svg'
import K7 from '../../assets/initial-hexes/K7.svg'
import L2 from '../../assets/initial-hexes/L2.svg'
import B4 from '../../assets/initial-hexes/B4.svg'
import mountain from '../../assets/initial-hexes/mountain.svg'
import empty from '../../assets/initial-hexes/empty.svg'
import water from '../../assets/initial-hexes/water.svg'

//tracks
import tX1 from '../../assets/tracks/tX1.svg'
import tX6 from '../../assets/tracks/tX6.svg'
import tX9 from '../../assets/tracks/tX9.svg'
import t23 from '../../assets/tracks/t23.svg'
import t25 from '../../assets/tracks/t25.svg'

export const INITIAL_MAP = { A3, A7, A13, B2, B14, C5, C13, D2, D8, D12, E1, E3, E11, F2, F4, F8, F14, G1, G3, G5, G13, H2, H4, H6, H14, I3, I5, I9, J2, J4, J6, K1, K3, K5, K7, L2, B4, mountain, empty, water } as const;
export const TRACKS = { t23, t25, tX1, tX6, tX9 } as const;
